//data set for shoping
const list = [
    {
      id: 1,
      title: "Photo Printed Tshirt",
      author: "Personalized for Men and Women",
      price: 589,
      img: "https://m.media-amazon.com/images/I/51veWpM8jKL._SX679_.jpg",
      amount: 1,
    },
    {
      id: 2,
      title: "AMERICAN CREW",
      author: "Polo Collar Cotton Poly Striped T-Shirt for Men",
      price: 98,
      img: "https://m.media-amazon.com/images/I/71LPcvl-4-L._SY879_.jpg",
      amount: 1,
    },
    {
      id: 3,
      title: "Amazon Brand ",
      author: "- Symbol Men's Regular Fit Polo Shirt",
      price: 143,
      img: "https://m.media-amazon.com/images/I/714zCgmX+JL._SY879_.jpg",
      amount: 1,
    },
    {
      id: 4,
      title: "AUSK T-Shirt",
      author: "for Mens Double Stripes on Chest",
      price: 657,
      img: "https://m.media-amazon.com/images/I/611lWcY76wL._SY879_.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "Cotton Henley",
      author: " Neck Full Sleeve Solid Regular Fit T-Shirt",
      price: 149,
      img: "https://m.media-amazon.com/images/I/61hy9jLQoaL._SY879_.jpg",
      amount: 1,
    },
    {
      id: 6,
      title: "SWADESI STUFF Regular Fit",
      author: " Striped Round Neck Half Sleeve 2 Line T-Shirt for Men",
      price: 135,
      img: "https://m.media-amazon.com/images/I/81gXXWFz-zL._SX679_.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: "Allen Solly",
      author: "Men's Regular Fit Polo",
      price: 693,
      img: "https://m.media-amazon.com/images/I/71eUwDk8z+L._SX569_.jpg",
      amount: 1,
    },
    {
      id: 8,
      title: "fanideaz Branded Mens",
      author: "Polo Tshirt for Men || Branded Tshirt for Men",
      price: 289,
      img: "https://m.media-amazon.com/images/I/61f4mm1VlRL._SY741_.jpg",
      amount: 1,
    },
    {
      id: 9,
      title: "Cotton Polo T-Shirt for Mens",
      author: "Polo T Shirt for Men ||Casual t Shirt for Men || Tshirt for Men Stylish",
      price: 580,
      img: "https://m.media-amazon.com/images/I/81wpgSt6OfL._SY879_.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "AUSK Round",
      author: "Neck Full Sleeve T-Shirt for Men",
      price: 386,
      img: "https://m.media-amazon.com/images/I/514suadMoJL.jpg",
      amount: 1,
    },
    {
      id: 11,
      title: "Crepe",
      author: "Printed Dress for Women",
      price: 220,
      img: "https://m.media-amazon.com/images/I/61dNgfOLAKL._SY741_.jpg",
      amount: 1,
    },
    {
      id: 12,
      title: "EYEBOGLER Regular Printed",
      author: " T-Shirt for Men(CTT344HS)",
      price: 457,
      img: "https://m.media-amazon.com/images/I/61GmEjXOdzL._SY879_.jpg",
      amount: 1,
    },
];

export default list;